services:
    sonata.admin.language:
        class: Limycuk\PribitokBundle\Admin\LanguageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Language", label: "List" }
        arguments:
            - ~
            - Limycuk\PribitokBundle\Entity\Language
            - ~
        calls:
            - [ setTranslationDomain, [LimycukArtGalleryBundle]]