services:
    entity_load.listener:
        class: Limycuk\PribitokBundle\EventListener\EntityLoader
        arguments: ["@service_container"]
        tags:
            - { name: doctrine.event_listener, event: postLoad }
